#!/usr/bin/env bash
# =============================================================================
# Voicebot Application — One-Command Setup
#
# Installs and configures:
#   1. Next.js frontend  (llm-tts-chat-app)  → voicebot-nextjs systemd service
#   2. Pipecat bot       (local-bot)          → voicebot-bot    systemd service
#
# Usage:
#   sudo bash setup.sh
#   sudo bash setup.sh --frontend-dir /path/to/llm-tts-chat-app \
#                      --bot-dir /path/to/local-bot
#
# Prerequisites:
#   - voicebot-stt  service running (port 8000)
#   - voicebot-llm  service running (port 8001 or configured in client.env)
#   - voicebot-tts  service running (port 8005)
# =============================================================================

set -euo pipefail

# ── Defaults ──────────────────────────────────────────────────────────────────
DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRONTEND_DIR="${FRONTEND_DIR:-/home/ubuntu/llm-tts-chat-app}"
BOT_DIR="${BOT_DIR:-/home/ubuntu/local-bot}"
SERVICE_USER="${SERVICE_USER:-ubuntu}"

# ── Argument parsing ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --frontend-dir) FRONTEND_DIR="$2"; shift 2 ;;
        --bot-dir)      BOT_DIR="$2";      shift 2 ;;
        --user)         SERVICE_USER="$2"; shift 2 ;;
        *) echo "[WARN] Unknown argument: $1"; shift ;;
    esac
done

# ── Helpers ───────────────────────────────────────────────────────────────────
info()  { echo "[INFO] $*"; }
warn()  { echo "[WARN] $*"; }
error() { echo "[ERROR] $*" >&2; exit 1; }

info "Deploy dir  : $DEPLOY_DIR"
info "Frontend dir: $FRONTEND_DIR"
info "Bot dir     : $BOT_DIR"
info "Service user: $SERVICE_USER"

# ── 0. Validate source directories ───────────────────────────────────────────
[[ -d "$FRONTEND_DIR" ]] || error "Frontend directory not found: $FRONTEND_DIR"
[[ -d "$BOT_DIR" ]]      || error "Bot directory not found: $BOT_DIR"
[[ -f "$FRONTEND_DIR/package.json" ]] || error "package.json not found in $FRONTEND_DIR"
[[ -f "$BOT_DIR/main.py" ]] || error "main.py not found in $BOT_DIR"

# ── 1. Create client.env from example if not present ─────────────────────────
if [[ ! -f "$DEPLOY_DIR/config/client.env" ]]; then
    warn "config/client.env not found — copying example"
    warn "Edit $DEPLOY_DIR/config/client.env with your credentials before using Twilio features"
    cp "$DEPLOY_DIR/config/client.env.example" "$DEPLOY_DIR/config/client.env"
fi
# Load env for port/URL references
set -o allexport
# shellcheck source=/dev/null
source "$DEPLOY_DIR/config/client.env"
set +o allexport

# ── 2. Install Node.js 20.x ──────────────────────────────────────────────────
NODE_MAJOR=20
if command -v node &>/dev/null; then
    CURRENT_NODE=$(node -v | sed 's/v//' | cut -d. -f1)
    if [[ "$CURRENT_NODE" -lt "$NODE_MAJOR" ]]; then
        info "Node.js $CURRENT_NODE detected — upgrading to $NODE_MAJOR..."
        curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash -
        apt-get install -y nodejs
    else
        info "Node.js $(node -v) OK"
    fi
else
    info "Installing Node.js $NODE_MAJOR..."
    curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash -
    apt-get install -y nodejs
fi

# ── 3. Build Next.js frontend ─────────────────────────────────────────────────
info "Installing Next.js dependencies..."
cd "$FRONTEND_DIR"
sudo -u "$SERVICE_USER" npm ci

info "Writing .env.local..."
sudo -u "$SERVICE_USER" bash -c "cat > '$FRONTEND_DIR/.env.local'" <<EOF
# Auto-generated by setup.sh — re-run setup to regenerate
ASR_API_URL=${ASR_API_URL:-http://localhost:8000}
LLM_API_URL=${LLM_API_URL:-http://localhost:8001}
TTS_API_URL=${TTS_API_URL:-http://localhost:8005}
ASR_MODEL=${ASR_MODEL:-Qwen/Qwen3-ASR-1.7B}
EOF

info "Building Next.js production bundle..."
sudo -u "$SERVICE_USER" npm run build

# ── 4. Install voicebot-nextjs systemd service ────────────────────────────────
info "Installing voicebot-nextjs service..."
sed \
    -e "s|__SERVICE_USER__|$SERVICE_USER|g" \
    -e "s|__FRONTEND_DIR__|$FRONTEND_DIR|g" \
    -e "s|__DEPLOY_DIR__|$DEPLOY_DIR|g" \
    "$DEPLOY_DIR/config/voicebot-nextjs.service" \
    > /etc/systemd/system/voicebot-nextjs.service

# ── 5. Set up Python venv for pipecat bot ─────────────────────────────────────
info "Creating Python venv for pipecat bot..."
cd "$BOT_DIR"
if [[ ! -d ".venv" ]]; then
    sudo -u "$SERVICE_USER" python3 -m venv .venv
fi
sudo -u "$SERVICE_USER" .venv/bin/pip install --upgrade pip --quiet
sudo -u "$SERVICE_USER" .venv/bin/pip install -r requirements.txt --quiet

# Install local packages if present
for pkg in Qwen3-ASR Qwen3-TTS; do
    if [[ -d "$BOT_DIR/$pkg" ]]; then
        info "Installing local package: $pkg"
        sudo -u "$SERVICE_USER" .venv/bin/pip install -e "$BOT_DIR/$pkg" --quiet
    fi
done

# ── 6. Install voicebot-bot systemd service ───────────────────────────────────
info "Installing voicebot-bot service..."
sed \
    -e "s|__SERVICE_USER__|$SERVICE_USER|g" \
    -e "s|__BOT_DIR__|$BOT_DIR|g" \
    -e "s|__DEPLOY_DIR__|$DEPLOY_DIR|g" \
    "$DEPLOY_DIR/config/voicebot-bot.service" \
    > /etc/systemd/system/voicebot-bot.service

# ── 7. Enable and start services ──────────────────────────────────────────────
info "Reloading systemd and enabling services..."
systemctl daemon-reload
systemctl enable voicebot-nextjs voicebot-bot

info "Starting voicebot-nextjs..."
systemctl restart voicebot-nextjs

info "Starting voicebot-bot..."
systemctl restart voicebot-bot

# ── 8. Status summary ─────────────────────────────────────────────────────────
sleep 2
echo ""
echo "========================================"
echo "  Voicebot Application — Setup Complete"
echo "========================================"
echo ""
echo "  Services:"
printf "    Next.js   (port 3000) : "
systemctl is-active voicebot-nextjs 2>/dev/null || true
printf "    Bot API   (port 5000) : "
systemctl is-active voicebot-bot 2>/dev/null || true
echo ""
echo "  Dependencies (verify running):"
echo "    voicebot-stt  (port 8000)"
echo "    voicebot-llm  (port 8001)"
echo "    voicebot-tts  (port 8005)"
echo ""
echo "  Logs:"
echo "    journalctl -u voicebot-nextjs -f"
echo "    journalctl -u voicebot-bot -f"
echo ""
echo "  Health check:"
echo "    bash $DEPLOY_DIR/healthcheck.sh"
